export const productos=  [
{name:"FORMITAS DE POLLO X 6 KG",price:2504,category:"BAS FROST"},                                      
{name:"NUGGETS DE POLLO X 6 KG",price:3512,category:"BAS FROST"},
{name:"NUGGETS DE POLLO CON CHEDDAR X 6 KG",price:4440,category:"BAS FROST"},      
{name:"FINGERS DE POLLO A LAS FINAS HIERBAS X 5 KG",price:3372,category:"BAS FROST"},       
{name:"MEDALLON DE POLLO X 6 KG",price:2504,category:"BAS FROST"  },                   
{name:"MEDALLON DE POLLO CON JAMON Y QUESO X 6 KG",price:3680,category:"BAS FROST"},       
{name:"MEDALLON DE POLLO CON ESPINACA X 6 KG",price:2904,category:"BAS FROST"} ,
{name:"MEDALLON DE MERLUZA X 6 KG",price:2248,category:"BAS FROST"},
{name:"MEDALLON DE MERLUZA CON ESPINACA X 6 KG",price:2632,category:"BAS FROST"},
{name:"MILANESA DE MERLUZA X 5 KG",price:3976,category:"BAS FROST"},
{name:"MILANESA DE PECHUGA X 5 KG",price:3208,category:"BAS FROST"},
{name:"BOCADITOS DE ESPINACA X 6 KG",price:2240,category:"BAS FROST"},
{name:"BOCADITOS DE PAPA Y MUZZARELLA X 6 KG",price:2592,category:"BAS FROST"},
{name:"BOCADITOS DE ZAPALLO Y MUZZARELLA X 6 KG",price:2592,category:"BAS FROST"},

{name:"PAPA BASTON CORTE TRADICIONAL X 15 KG",price:4216,category:"MC CAIN FOOD SERVICE"},
{name:"PAPA SMILES (CARITA) X 9 KG",price:4000,category:"MC CAIN FOOD SERVICE"},
{name:"PAPA NOISETTES X 10 KG",price:4448,category:"MC CAIN FOOD SERVICE"},
{name:"PAPA BASTON CORTE FINO X 18 KG",price:5312,category:"MC CAIN FOOD SERVICE"},
{name:"PAPA SURE CRISP X 15 KG",price:4932,category:"MC CAIN FOOD SERVICE"},
{name:"PAPA SURE CRISP CORTE FINO X 18 KG",price:6176,category:"MC CAIN FOOD SERVICE"},
{name:"PAPAS GASTRONOMICAS X 15 KG",price:4216,category:"MC CAIN FOOD SERVICE"},
{name:"PAPA CRINKLE X 12.5 KG",price:3864,category:"MC CAIN FOOD SERVICE"},
{name:"PIZZA SIBARITA MUZZARELLA 640 GR X 10 UNIDADES",price:3360,category:"MC CAIN FOOD SERVICE"},

{name:"PAPA BASTON CORTE TRADICIONAL 12 X 720 GR",price:3168,category:"MC CAIN RETAIL"},
{name:"PAPA NOISETTES 18 X 500 GR",price:4864,category:"MC CAIN RETAIL"},
{name:"PAPA SMILES (CARITA) 12 X 600 GR",price:4360,category:"MC CAIN RETAIL"},

{name:"AROS DE PAPA X 9 KG",price:3692,category:"MC CAIN APPETIZERS"},
{name:"AROS DE CEBOLLA X 10 KG",price:7136,category:"MC CAIN APPETIZERS"},
{name:"GUACAMOLE 12 X 450 GR",price:7600,category:"MC CAIN APPETIZERS"},
{name:"PULPA DE PALTA 12 X 450 GR",price:7600,category:"MC CAIN APPETIZERS"},

{name:"BASTONES DE MUZZARELLA X 6 KG (3 X 2 KG)",price:5688,category:"MC CAIN PICKERS"},
{name:"BITE CHEDDAR Y PANCETA X 6 KG (3 X 2 KG)",price:4092,category:"MC CAIN PICKERS"},
{name:"BITE ESPINACA Y QUESO X 6 KG (3 X 2 KG)",price:3640,category:"MC CAIN PICKERS"},
{name:"TRIANGULO DE MUZZARELLA X 6 KG (3 X 2 KG)",price:5688,category:"MC CAIN PICKERS"},
{name:"PAPA PAPRIKA/PEPPER STYLE X 18 KG (8 X 2,25 KG)",price:6232,category:"MC CAIN PICKERS"},

{name:"ACELGA X 10 KG",price:3960,category:"MC CAIN VEGETALES"},
{name:"ARVEJAS X 10 KG",price:4720,category:"MC CAIN VEGETALES"},
{name:"BROCOLI X 10 KG",price:5056,category:"MC CAIN VEGETALES"},
{name:"CHAUCHA X 10 KG",price:4260,category:"MC CAIN VEGETALES"},
{name:"CHAMPIÑONES X 10 KG",price:5636,category:"MC CAIN VEGETALES"},
{name:"CHOCLO X 10 KG",price:4676,category:"MC CAIN VEGETALES"},
{name:"ESPINACA X 10 KG",price:4208,category:"MC CAIN VEGETALES"},
{name:"ESPINACA PICADA X 10 KG",price:4112,category:"MC CAIN VEGETALES"},
{name:"MIX JARDINERA X 10 KG",price:4464,category:"MC CAIN VEGETALES"},

{name:"NUGGETS DE POLLO CROCANTES X 6 KG",price:3888 ,category:"ARTICO"},
{name:"FORMITAS DE POLLO X 6 KG",price:3136 ,category:"ARTICO"},
{name:"FORMITAS DE MERLUZA X 6 KG",price:2360 ,category:"ARTICO"},
{name:"MEDALLON DE POLLO X 6 KG",price:3136 ,category:"ARTICO"},
{name:"MEDALLON DE POLLO CON ESPINACA X 6 KG",price:4200 ,category:"ARTICO"},
{name:"MEDALLON DE POLLO CON JAMON Y QUESO X 6 KG",price:4612 ,category:"ARTICO"},
{name:"MEDALLON DE MERLUZA X 6 KG",price:2360 ,category:"ARTICO"},
{name:"MEDALLON DE MERLUZA CON ESPINACA X 6 KG",price:2496 ,category:"ARTICO"},
{name:"MINI MILANESA DE MERLUZA A LA ROMANA X 6 KG",price:2984 ,category:"ARTICO"},
{name:"MILANESA DE MERLUZA A LA ROMANA X 5 KG",price:4128 ,category:"ARTICO"},
{name:"MILANESA DE MERLUZA X 6 KG",price:4956 ,category:"ARTICO"},
{name:"MILANESA DE MERLUZA FINAS HIERBAS X 6 KG",price:5216 ,category:"ARTICO"},
{name:"CROQUETAS DE PAPA, JAMON Y QUESO X 6 KG",price:3180 ,category:"ARTICO"},
{name:"MINI CROQUETAS DE JAMON Y QUESO X 6 KG",price:3256 ,category:"ARTICO"},
{name:"MINI CROQUETAS DE ESPINACA X 6 KG",price:3256 ,category:"ARTICO"},
{name:"BARRITAS DE MERLUZA X 6 KG",price:2360 ,category:"ARTICO"},
{name:"BARRITAS DE MUZZARELLA X 6 KG",price:5400 ,category:"ARTICO"},
{name:"TIRITAS DE POLLO A LAS FINAS HIERBAS X 6 KG",price:3876 ,category:"ARTICO"},
{name:"PECHUGUITAS CRISPY X 6 KG",price:4248 ,category:"ARTICO"},
{name:"MINI PECHUGAS DE POLLO AL VERDEO X 6 KG",price:4416 ,category:"ARTICO"},

{name:"NUGGETS DE POLLO X 5 KG",price:2944 ,category:"GRANGY'S"},
{name:"PATITAS DE POLLO X 5 KG",price:2224 ,category:"GRANGY'S"},
{name:"PATITAS DE POLLO CON JAMON Y QUESO X 5 KG",price:2576 ,category:"GRANGY'S"},
{name:"PATITAS DE POLLO CON ESPINACA Y QUESO X 5 KG",price:2576 ,category:"GRANGY'S"},
{name:"MEDALLON DE POLLO X 5 KG",price:2224 ,category:"GRANGY'S"},
{name:"MEDALLON DE POLLO CON JAMON Y QUESO X 5 KG",price:2576 ,category:"GRANGY'S"},
{name:"MEDALLON DE POLLO CON ESPINACA Y QUESO X 5 KG",price:2576 ,category:"GRANGY'S"},
{name:"MEDALLON DE MERLUZA X 5 KG",price:1840 ,category:"GRANGY'S"},
{name:"MEDALLON DE MERLUZA CON ESPINACA Y QUESO X 5 KG",price:2164 ,category:"GRANGY'S"},
{name:"FORMITA DE MERLUZA X 5 KG",price:1840 ,category:"GRANGY'S"},
{name:"BASTONES DE MERLUZA X 5 KG",price:1840 ,category:"GRANGY'S"},
{name:"BOCADITOS DE ESPINACA X 5 KG",price:1928 ,category:"GRANGY'S"},
{name:"BOCADITOS DE CAPRESSE X 5 KG",price:3944 ,category:"GRANGY'S"},
{name:"BOCADITOS DE JAMON Y QUESO X 5 KG",price:3944 ,category:"GRANGY'S"},
{name:"BOCADITOS DE MUZZARELLA X 5 KG",price:3944 ,category:"GRANGY'S"},
{name:"BOCADITOS DE PAPA Y QUESO X 5 KG",price:2240 ,category:"GRANGY'S"},
{name:"BOCADITOS DE CALABAZA X 5 KG",price:2240 ,category:"GRANGY'S"},


{name:"BOCADITOS DE POLLO PREMIUM X 5 KG",price:2144 ,category:"GRANJA 3 ARROYOS"},
{name:"FORMADO CRISPY X 5 KG",price:3512 ,category:"GRANJA 3 ARROYOS"},
{name:"HAMBURGUESA DE POLLO X 5 KG",price:3096 ,category:"GRANJA 3 ARROYOS"},
{name:"MEDALLON DE POLLO X 5 KG",price:2264 ,category:"GRANJA 3 ARROYOS"},
{name:"NUGGETS A LA TEMPURA X 5 KG",price:2864 ,category:"GRANJA 3 ARROYOS"},
{name:"POCHOCLO DE POLLO REBOZADO X 5 KG",price:2440 ,category:"GRANJA 3 ARROYOS"},
{name:"RICOSAURIOS DE POLLO X 5 KG",price:2672 ,category:"GRANJA 3 ARROYOS"},


{name:"NUGGETS DE POLLO X 6 KG",price:3696 ,category:"SADIA"},
{name:"SUPREMITAS REBOZADAS X 6 KG",price:3984 ,category:"SADIA"},
{name:"PECHUGAS REBOZADAS DE POLLO X 6 KG",price:3944 ,category:"SADIA"},


{name:"FINGERS DE POLLO X 5 KG",price:2928 ,category:"CALISA"},
{name:"FINGERS DE POLLO CAPRESE X 5 KG",price:2928 ,category:"CALISA"},
{name:"HAMBURGUESAS DE POLLO BIGGER BURGER X 5 KG",price:3432 ,category:"CALISA"},
{name:"FORMADOS DE POLLO X 5 KG",price:2928 ,category:"CALISA"},
{name:"MEDALLON DE POLLO X 5 KG",price:2448 ,category:"CALISA"},
{name:"MEDALLON DE POLLO CON ESPINACA Y QUESO X 5 KG",price:3024 ,category:"CALISA"},
{name:"MEDALLON DE POLLO CON JAMON Y QUESO X 5 KG",price:3024 ,category:"CALISA"},


{name:"NOT BURGER X 31 PACKS (2 X 80 GR)",price:9656 ,category:"NOTCO"},
{name:"NOT BURGER XL X 21 PACKS (2 X 120 GR)",price:8704 ,category:"NOTCO"},
{name:"NOT BURGER X 100 U (80 GR)",price:10440 ,category:"NOTCO"},
{name:"NOT CHICKEN BURGER RETAIL X 25 PACKS (2 X 100 GR)",price:9804 ,category:"NOTCO"},
{name:"NOT CHICKEN CRISPY X 25 PACKS (2 X 100 GR)",price:9016 ,category:"NOTCO"},
{name:"NOT CHICKEN NUGGETS (5 X 1 KG)",price:8288 ,category:"NOTCO"},  


{name:"PATITAS DE POLLO X 6 KG",price:3336 ,category:"SOLIMENO"},
{name:"MEDALLON DE POLLO X 6 KG",price:3168 ,category:"SOLIMENO"},
{name:"TORTILLAS DE ESPINACA X 6 KG",price:2928 ,category:"SOLIMENO"},
{name:"RABAS REBOZADAS X 5 KG",price:9264 ,category:"SOLIMENO"},  


{name:"HAMBURGUESAS POROTOS NEGROS Y HONGOS X 48 U (12 X 4 U)",price:2528,category:"KAIA"},
{name:"HAMBURGUESAS GARBANZO Y CALABAZA X 48 U (12 X 4 U)",price:2528,category:"KAIA"},
{name:"HAMBURGUESAS QUINOA, TOMATE Y ESP. X 48 U (12 X 4 U)",price:2528,category:"KAIA"},
{name:"HAMBURGUESAS LENTEJAS Y VERDEO X 48 U (12 X 4 U)",price:2528,category:"KAIA"},
{name:"HAMBURGUESAS ADZUKI Y PUERRO X 48 U (12 X 4 U)",price:2528,category:"KAIA"},
{name:"NUGGETS QUINOA (12 BOLSAS X 250 GR)",price:2528 ,category:"KAIA"},


{name:"MIX PRIMAVERA X 10 KG",price:3.728 ,category:"GREENS"},


{name:"HAMBURGUESAS DE CARNE X 60 U (80 GR C/U)",price:5132,category:"PATY"},
{name:"HAMBURGUESAS DE CARNE GRANDES X 40 U (125 GR C/U)",price:6408 ,category:"PATY"},


{name:"HAMBURGUESAS DE CARNE X 72 U (55 GR C/U)",price:3452,category:"FRIAR"},
{name:"HAMBURGUESAS DE CARNE X 60 U (80 GR C/U)",price:4160,category:"FRIAR"},
{name:"HAMBURGUESAS DE CARNE X 40 U (110 GR C/U)",price:3664,category:"FRIAR"},
{name:"MEDALLONES DE CARNE X 60 U (80 GR C/U)",price:2544,category:"FRIAR"},
{name:"MEDALLONES DE CARNE X 40 U (110 GR C/U)",price:2264,category:"FRIAR"},


{name:"ACELGA TRITURADA X 20 KG",price:4584 ,category:"CIFSA"},
{name:"ARANDANO ENTERO X 10 KG",price:6840 ,category:"CIFSA"},
{name:"CHOCLO EN GRANOS X 25 KG",price:9468 ,category:"CIFSA"},
{name:"DURAZNO CUBETEADO X 10 KG",price:4272 ,category:"CIFSA"},
{name:"FRAMBUESA ENTERA X 10 KG",price:17072 ,category:"CIFSA"},  
{name:"FRUTILLA ENTERA X 10 KG",price:4560 ,category:"CIFSA"},
{name:"MANGO CUBETEADO X 10 KG",price:6344 ,category:"CIFSA"},
{name:"PULPA DE ACAI X 10 KG",price:11096 ,category:"CIFSA"},  
{name:"PULPA DE MARACUYA (SIN SEMILLA) X 10 KG",price:6748 ,category:"CIFSA"},
{name:"MIX BERRIES (SIN FRUTILLA) X 10 KG",price:12184 ,category:"CIFSA"},  
{name:"MIX BERRIES (CON FRUTILLA) X 10 KG",price:10680 ,category:"CIFSA"},  
{name:"MORA ENTERA X 10 KG",price:10824 ,category:"CIFSA"},  

{name:"MILANESA DE SOJA 25 X 4 U",price:6124,category:"ALKIMYK"},
{name:"MILANESA DE SOJA C/BROCOLI Y CEBOLLA 15 X 4 U",price:4416,category:"ALKIMYK"},
{name:"MILANESA DE SOJA CAPRESE 15 X 4 U",price:5240,category:"ALKIMYK"},
{name:"MILANESA DE SOJA C/JAMON Y QUESO 15 X 4 U",price:5240,category:"ALKIMYK"},
{name:"MILANESA DE SOJA C/ROQUEFORT 15 X 4 U",price:5888,category:"ALKIMYK"},
{name:"MILANESA DE SOJA C/ACEITUNA Y QUESO 15 X 4 U",price:5240,category:"ALKIMYK"},
{name:"MILANESA DE SOJA C/CALABAZA Y CURCUMA 15 X 4 U",price:4416,category:"ALKIMYK"},
{name:"MILANESA DE SOJA C/CEBOLLA AL OREGANATO 15 X 4 U",price:4416,category:"ALKIMYK"},
{name:"MILANESA DE SOJA C/ESPINACA Y MORRONES 15 X 4 U",price:4416,category:"ALKIMYK"},
{name:"PATITAS DE SOJA 18 X 380 GR",price:4240,category:"ALKIMYK"},



 {name:"REBOZADOR 14-80 X 25 KG",price:3268,make:"BAS",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR X 25 KG",price:3268,make:"BAS",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR MIX (NATURAL) X 20 KG",price:2839,make:"BAS",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR COLOR X 20 KG",price:2899,make:"BAS",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR CRUNCH X 5 KG",price:1545,make:"BAS",category:"PAN RALLADO Y REBOZADOR"},
 {name:"PAN RALLADO X 20 KG",price:2899,make:"BAS",category:"PAN RALLADO Y REBOZADOR"},
 {name:"PAN RALLADO CASERO X 5 KG",price:72,make:"BAS",category:"PAN RALLADO Y REBOZADOR"},
 
 {name:"REBOZADOR PYC X 25 KG",price:3498,make:"BAMMI",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR X 25 KG",price:3902,make:"BAMMI",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR 14-80 X 25 KG",price:3902,make:"BAMMI",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR COLOR M X 25 KG",price:4038,make:"BAMMI",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR BLANCO X 25 KG",price:4038,make:"BAMMI",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR R33 X 20 KG",price:3477,make:"BAMMI",category:"PAN RALLADO Y REBOZADOR"},
 {name:"PAN RALLADO X 20 KG",price:3298,make:"BAMMI",category:"PAN RALLADO Y REBOZADOR"},
 
 {name:"REBOZADOR X 25 KG",price:3264,make:"MANDY",category:"PAN RALLADO Y REBOZADOR"},
 
 {name:"REBOZADOR X 10 KG",price:1505,make:"CRYSTAL",category:"PAN RALLADO Y REBOZADOR"},
 {name:"REBOZADOR X 25 KG",price:3477,make:"CRYSTAL",category:"PAN RALLADO Y REBOZADOR"},
 
 {name:"BATTER MILANESA CON HUEVO X KG",price:474,make:"BAS",category:"ALBUMINAS Y OVOPRODUCTOS"},
 {name:"BATTER MILANESA CON HUEVO X 5 KG",price:2125,make:"BAS",category:"ALBUMINAS Y OVOPRODUCTOS"},
 {name:"BATTER MILANESA CON HUEVO X 30 KG",price:11994,make:"BAS",category:"ALBUMINAS Y OVOPRODUCTOS"},
 {name:"BATTER MASAJEO X 5 KG",price:2125,make:"BAS",category:"ALBUMINAS Y OVOPRODUCTOS"},
 {name:"OVO PLUS X KG",price:700,make:"BAS",category:"ALBUMINAS Y OVOPRODUCTOS"},
 {name:"OVO PLUS X 5 KG",price:3247,make:"BAS",category:"ALBUMINAS Y OVOPRODUCTOS"},
 {name:"OVO PLUS X 30 KG",price:18734,make:"BAS",category:"ALBUMINAS Y OVOPRODUCTOS"},
 {name:"HUEVO EN POLVO (ENTERO) X 5 KG",price:7871,make:"BAS",category:"ALBUMINAS Y OVOPRODUCTOS"},
 
 {name:"ADOBO PIZZA X KG",price:562,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"AJI MOLIDO X KG",price:450,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"CAYENA X KG",price:562,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"CHIMICHURRI DESHIDRATADO X KG",price:537,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"COMINO MOLIDO X KG",price:662,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"CONDIMENTO CURRY X KG",price:474,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"CONDIMENTO P/ARROZ X KG",price:487,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"CONDIMENTO P/MATAMBRE X KG",price:537,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"CONDIMENTO P/MILANESAS X KG",price:549,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"CONDIMENTO P/PASTAS X KG",price:587,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"CORIANDRO MOLIDO X KG",price:337,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"ESPECIAS SURTIDAS X KG",price:487,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"ESTRAGON X KG",price:2380,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"LAUREL EN HOJA X KG",price:974,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"MIX DE SEMILLAS X KG",price:662,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"NUEZ MOSCADA MOLIDA X KG",price:1748,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"OREGANO X KG",price:700,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PIMENTON X KG",price:587,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PIMENTON X 25 KG",price:13430,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PIMENTON AHUMADO X KG",price:825,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PIMIENTA BLANCA MOLIDA B X KG",price:57,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PIMIENTA BLANCA MOLIDA B X 25 KG",price:13430,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PIMIENTA BLANCA EN GRANO X KG",price:1811,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PIMIENTA NEGRA MOLIDA X KG",price:1037,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PIMIENTA NEGRA EN GRANO X KG",price:1037,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PROVENZAL X KG",price:599,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"PROVENZAL X 25 KG",price:13736,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"ROMERO X KG",price:750,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},
 {name:"TOMILLO X KG",price:774,make:"BAS",category:"ESPECIAS Y CONDIMENTOS"},

 
 {name:"ADOBO PIZZA",price:1199,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"AJI MOLIDO",price:1097,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"AJO EN GRANO",price:1301,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"CHIMICHURRI DESHIDRATADO",price:1148,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"FINAS HIERBAS",price:1403,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"OREGANO",price:1199,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"PIMENTON",price:1097,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"PIMIENTA NEGRA EN GRANO",price:1598,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"PIMIENTA NEGRA MOLIDA",price:1598,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"PROVENZAL",price:1449,description:"(40 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 
 {name:"ADOBO PIZZA",price:330,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"AJI MOLIDO",price:303,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"AJO EN GRANO",price:357,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"CHIMICHURRI DESHIDRATADO",price:316,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"FINAS HIERBAS",price:383,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"OREGANO",price:330,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"PIMENTON",price:303,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"PIMIENTA NEGRA EN GRANO",price:439,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"PIMIENTA NEGRA MOLIDA",price:439,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},
 {name:"PROVENZAL",price:399,description:"PACK (10 X 25 GR)",make:"BAS",category:"ESPECIAS Y CONDIMENTOS RETAIL"},

 {name:"AJO EN GRANO X KG",price:762,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"AJO EN POLVO X KG",price:487,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"AJO EN POLVO X 30 KG",price:13490,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"ALBAHACA EN HOJAS X KG",price:625,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"CEBOLLA EN ESCAMAS X KG",price:762,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"CEBOLLA EN ESCAMAS X 20 KG",price:14238,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"MORRON EN POLVO X KG",price:812,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"MORRON EN ESCAMAS X KG",price:1913,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"PAPA EN ESCAMAS X 5 KG",price:3050,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"PAPA EN ESCAMAS X 20 KG",price:8466,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 {name:"PEREJIL X KG",price:837,make:"BAS",category:"VERDURAS DESHIDRATADAS"},
 
 {name:"ESPINACA EN POLVO X KG",price:1190,category:"VERDURAS DESHIDRATADAS"},
 {name:"ESPINACA EN POLVO X 20 KG",price:18437,category:"VERDURAS DESHIDRATADAS"},
 {name:"ESPINACA EN ESCAMAS X 10 KG",price:10727,category:"VERDURAS DESHIDRATADAS"},
 {name:"ESPINACA EN ESCAMAS X KG",price:1340,category:"VERDURAS DESHIDRATADAS"},
 {name:"PURE DE PAPA LAFQUEN 15 X 100 G",price:1540,category:"VERDURAS DESHIDRATADAS"},
 {name:"ZAPALLO DESHIDRATADO X 20 KG",price:21905,category:"VERDURAS DESHIDRATADAS"},
 {name:"ZAPALLO DESHIDRATADO X 5 KG",price:7090,category:"VERDURAS DESHIDRATADAS"},
 {name:"ZAPALLO DESHIDRATADO X 2 KG",price:2835,category:"VERDURAS DESHIDRATADAS"},

 {name:"INTEGRAL CHORIZO PLUS X 1 KG",price:474,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL CHORIZO PLUS X 5 KG",price:2125,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL CHORIZO PLUS X 30 KG",price:11994,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL CHORIZO COLORADO X 1 KG",price:575,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL CHORIZO FRESCO X 5 KG",price:2125,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL CHORIZO FRESCO X 30 KG",price:11994,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL CHORIZO SECO X 1 KG",price:450,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL FORMITAS X 30 KG",price:12368,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA PLUS X 1 KG",price:474,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA PLUS X 5 KG",price:2125,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA PLUS X 30 KG",price:11994,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA CARNE X 1 KG",price:474,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA CARNE X 5 KG",price:2125,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA CARNE X 30 KG",price:11994,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA POLLO X 1 KG",price:474,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA POLLO X 5 KG",price:2125,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA AHUMADA PLUS X 1 KG",price:474,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL HAMBURGUESA AHUMADA PLUS X 5 KG",price:2125,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL LONGANIZA X 1 KG",price:474,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL LONGANIZA X 5 KG",price:2125,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL SALAME X 5 KG",price:2185,make:"BAS",category:"INTEGRALES"},
 {name:"INTEGRAL SALCHICHA FRESCA X 5 KG",price:2125,make:"BAS",category:"INTEGRALES"},

 {name:"CURCUMA X KG",price:575,make:"BAS",category:"COLORANTES, CONSERVANTES y MEJORADORES"},
 {name:"GLUTAMATO MONOSODICO X KG",price:850,make:"BAS",category:"COLORANTES, CONSERVANTES y MEJORADORES"},
 
 {name:"BETA MORRON X 2 LTS",price:5381,make:"MANDY",category:"COLORANTES, CONSERVANTES y MEJORADORES"},
 {name:"BETACAROTENO X 5 LTS.",price:5126,make:"MANDY",category:"COLORANTES, CONSERVANTES y MEJORADORES"},
 {name:"PROPIONATO DE CALCIO X KG",price:864,make:"MANDY",category:"COLORANTES, CONSERVANTES y MEJORADORES"},

 {name:"CALDO POLLO X 1 KG",price:737,make:"BAS",category:"CALDOS, SABORIZANTES Y OTROS"},
 {name:"CALDO VERDURA X 1 KG",price:737,make:"BAS",category:"CALDOS, SABORIZANTES Y OTROS"},
 {name:"SABOR CARNE ASADA X 1 KG",price:850,make:"BAS",category:"CALDOS, SABORIZANTES Y OTROS"},
 {name:"SABOR CERDO X 1 KG",price:837,make:"BAS",category:"CALDOS, SABORIZANTES Y OTROS"},
 {name:"SABOR HUMO LIQUIDO X 1 LT",price:910,make:"BAS",category:"CALDOS, SABORIZANTES Y OTROS"},
 {name:"SABOR JAMON X 1 KG",price:837,make:"BAS",category:"CALDOS, SABORIZANTES Y OTROS"},
 {name:"SABOR POLLO X 1 KG",price:837,make:"BAS",category:"CALDOS, SABORIZANTES Y OTROS"},
 {name:"SABOR POLLO GRILLE X 1 KG",price:837,make:"BAS",category:"CALDOS, SABORIZANTES Y OTROS"},
 {name:"SABOR QUESO PARMESANO X 1 KG",price:799,make:"BAS",category:"CALDOS, SABORIZANTES Y OTROS"},

]
export const categorias = [   
    {name:"BAS FROST"},
    {name:"MC CAIN FOOD SERVICE"},
    {name:"MC CAIN RETAIL"},
    {name:"MC CAIN APPETIZERS"},
    {name:"MC CAIN PICKERS"},
    {name:"MC CAIN VEGETALES"},
    {name:"ARTICO"},
    {name:"GRANGY'S"},
    {name:"GRANJA 3 ARROYOS"},
    {name:"SADIA"},
    {name:"CALISA"},
    {name:"NOTCO"},
    {name:"SOLIMENO"},
    {name:"KAIA"},
    {name:"GREENS"},
    {name:"PATY"},
    {name:"FRIAR"},
    {name:"CIFSA"},
    {name:"ALKIMYK"},
    {name:"PAN RALLADO Y REBOZADOR"},
    {name:"ALBUMINAS Y OVOPRODUCTOS"},
    {name:"ESPECIAS Y CONDIMENTOS"},
    {name:"ESPECIAS Y CONDIMENTOS RETAIL"},
    {name:"VERDURAS DESHIDRATADAS"},
    {name:"INTEGRALES"},
    {name:"COLORANTES, CONSERVANTES y MEJORADORES"},
    {name:"CALDOS, SABORIZANTES Y OTROS"},
    ]

